import Footer from "@/components/Footer";
import "./globals.css";
import type { Metadata } from "next";
import { Manjari } from "next/font/google";
import { MainHeader } from "@/components/Header";

const font = Manjari({ weight: ["100", "400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Plant Buds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="se">
      <body className={`${font.className} `}>
        <MainHeader />
        <main className="pt-[165px] max-w-5xl m-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
