import Nav from "@/components/Nav/MenuNav";
import "./globals.css";
import type { Metadata } from "next";
import { Manjari } from "next/font/google";

const font = Manjari({ weight: ["100", "400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Plant Buds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>{children}</body>
    </html>
  );
}
